name: mindwave_mobile2_example
description: "Demonstrates how to use the mindwave_mobile2 plugin."

publish_to: "none"

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  mindwave_mobile2:
    path: ../

  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  rxdart: ^0.27.7
  table_calendar: ^3.0.9
  lottie: ^3.1.2
  flutter_svg: ^2.0.10+1
  audioplayers: ^5.2.1
  animated_text_kit: ^4.2.2
  flame: ^1.15.0
  flame_tiled: ^1.18.4
  logging: ^1.2.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  go_router: ^14.2.0
  games_services: ^4.0.1
  syncfusion_flutter_gauges: ^26.1.38
  timer_count_down: ^2.2.0
  percent_indicator: ^4.2.3
  linear_progress_bar: "^1.1.1"
  pausable_timer: ^3.1.0+3

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_blue_plus:
  fl_chart:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.1
  local_auth: ^2.2.0
  flutter_locales: ^3.0.1

flutter:
  assets:
    - assets/tiles/
    - assets/Images/Terrain/
    - assets/Visualize_1.mp3
    - assets/B-BALANCE_BRAIN_AND_BODY.mp3
    - assets/guided_1.mp3
    - assets/mindwave.jpg

  uses-material-design: true
