name: mindwave_mobile2
description: "A Plugin that provides a Flutter interface for Neurosky Mindwave Mobile 2 headset."
version: 1.0.0+2
homepage: https://github.com/PrinceEGY/mindwave_mobile2

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flame_tiled: ^1.18.4
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: org.mindwave.mindwave_mobile2
        pluginClass: MindwaveMobile2Plugin